FROM alpine:latest

ARG VOCAB_PG_HOST
ARG VOCAB_PG_DATABASE
ARG VOCAB_PG_SCHEMA
ARG VOCAB_PG_USER
ARG VOCAB_PG_PASSWORD

WORKDIR /app

COPY ./vocab_script/ /app/

RUN apk add --no-cache --upgrade bash

RUN chmod +x ./scripts/load_omop_vocab.

RUN sleep 100

CMD bash ./scripts/load_omop_vocab.sh