# Use the official postgres image as the base image
FROM postgres:16.0-alpine3.18

# Copy the SQL script to initialize the database
COPY ./base_sql_scripts/* /docker-entrypoint-initdb.d/

# Expose the default postgres port
EXPOSE 5432
