FROM alpine:3.12

ARG VOCAB_PG_HOST
ARG VOCAB_PG_DATABASE
ARG VOCAB_PG_SCHEMA
ARG VOCAB_PG_USER
ARG VOCAB_PG_PASSWORD

WORKDIR /app

COPY ./vocab_script/ /app/

RUN apk add --no-cache --upgrade bash

RUN chmod +x ./scripts/vocab_loader.sh

CMD bash ./scripts/vocab_loader.sh