apiVersion: v1
kind: Secret
metadata:
  name: omop-secrets
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM= # postgres in base64
  POSTGRES_PASSWORD: bXlzZWNyZXRwYXNzd29yZA== # mysecretpassword in base64